<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "frontend_user"
 *
 * Auto generated by Extension Builder 2015-04-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => 'd-mind Cookieman',
    'description' => 'Provide multi-categogory cookie banner for selective opt-ins',
    'category' => 'frontend',
    'author' => 'Jonas Eberle',
    'author_email' => 'jonas.eberle@d-mind.de',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0-dev',
    'constraints' => array(
        'depends' => array(),
        'conflicts' => array(),
        'suggests' => array(),
    ),
);
