#!/bin/bash

composer cookieman:test:cgl
result=$?
if [ $result -eq 127 ];then
    # this normally means that composer could not find the command
    echo "php-cs-fixer is not installed. Please run ‹composer install› to do so."
    # be kind
    exit 0
elif [ $result -ne 0 ];then
     # https://github.com/FriendsOfPHP/PHP-CS-Fixer#exit-code
     echo "--------------------------------------------------------------------"
     echo "  >> ERROR: There was a coding guideline problem in one or more of  "
     echo "              your php files.                                       "
     echo "   Please refer to [1] for details on the coding guidelines         "
     echo "   Please refer to [2] for details on contribution                  "
     echo "   [1] https://docs.typo3.org/typo3cms/CoreApiReference/CodingGuidelines/Index.html"
     echo "   [2] https://docs.typo3.org/typo3cms/ContributionWorkflowGuide/   "
     echo "--------------------------------------------------------------------"
     echo "   Your commit is being aborted ... Fix and try again!"
     echo "   You can try automatic fixing with the composer script ‹composer cookieman:fix:cgl›"
     exit 1
fi
exit 0
