#!/bin/bash
# not a ddev-command. This is run pre-start to copy your .gitconfig into the container.

if [ -e ~/.gitconfig ]; then
  echo copying your .gitconfig...
  cp -L ~/.gitconfig .ddev/homeadditions/
else
  echo ".gitconfig not found (you should not commit or use ‹composer release:create› in the container before adding it)"
fi
