#!/bin/bash

## Description: installs git hooks for pre-commit checking to your local .git
## Usage: install-git-hooks

endC="\033[0m"
red="\033[0;31m"
greenb="\033[1;32m"
successC=$greenb
errorC=$red

echo Installing git hooks...
rsync -a /mnt/ddev_config/template/git-hooks/ "/var/www/html"/.git/hooks/ \
  && printf "${successC}✓${endC} OK.\n" \
  || printf "${errorC}🞩${endC} Error.\n"
