services:
  Dmind\Cookieman\DataProcessing\TypoScriptSettingsProcessor:
    autowire: true
    autoconfigure: false
    public: true
  Dmind\Cookieman\ViewHelpers\ShownTrackingObjectsViewHelper:
    public: true
