services:
  web:
    environment:
      - PHP_IDE_CONFIG=serverName=${DDEV_SITENAME}
      - TYPO3_CONTEXT=Development/Local
      - BROWSERSTACK_USERNAME=${BROWSERSTACK_USERNAME}
      - BROWSERSTACK_ACCESS_KEY=${BROWSERSTACK_ACCESS_KEY}
